// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-1POEm8o5z3_ELRpYscTSq8KcIdN7uM',
    appId: '1:359357413196:web:aeb6f34b3cc9887f4a01e9',
    messagingSenderId: '359357413196',
    projectId: 'peticiones-fireb2',
    authDomain: 'peticiones-fireb2.firebaseapp.com',
    storageBucket: 'peticiones-fireb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCyD5S6w5LdCY4O8eeS8X1BLyOSoYhydg',
    appId: '1:359357413196:android:90f726796e0033014a01e9',
    messagingSenderId: '359357413196',
    projectId: 'peticiones-fireb2',
    storageBucket: 'peticiones-fireb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPJTGChJNH3F91ZbkTP2HZTsgL4-SF1M',
    appId: '1:359357413196:ios:219cb9b5cce1f7f44a01e9',
    messagingSenderId: '359357413196',
    projectId: 'peticiones-fireb2',
    storageBucket: 'peticiones-fireb2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwPJTGChJNH3F91ZbkTP2HZTsgL4-SF1M',
    appId: '1:359357413196:ios:219cb9b5cce1f7f44a01e9',
    messagingSenderId: '359357413196',
    projectId: 'peticiones-fireb2',
    storageBucket: 'peticiones-fireb2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh-1POEm8o5z3_ELRpYscTSq8KcIdN7uM',
    appId: '1:359357413196:web:ec3e6f22ccd3aab94a01e9',
    messagingSenderId: '359357413196',
    projectId: 'peticiones-fireb2',
    authDomain: 'peticiones-fireb2.firebaseapp.com',
    storageBucket: 'peticiones-fireb2.firebasestorage.app',
  );
}
